config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  root to: 'pages#home'

  get 'restaurants', to: 'restaurants#index'
  get 'restaurants/:id', to: 'restaurants#show', as: 'restaurant'
  post 'restaurants', to: 'restaurants#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  RESTAURANTS = {
    1 => { name: "Dishoom", address: "Shoreditch, London", category: "indian" },
    2 => { name: "Sushi Samba", address: "City, London", category: "japanese" }
  }

  def index
    @category = params["food_type"]
    if params["food_type"].blank?
      @restaurants = RESTAURANTS
    else
      @restaurants = RESTAURANTS.select { |id, restaurant| restaurant[:category] == @category }
    end
    # @restaurants = Restaurant.all
  end

  def create
    # raise
    # Restaurant.new(name: params[:name], address: params[:name])
  end

  def show
    @restaurant = RESTAURANTS[params[:id].to_i]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thespoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
  <footer>
    Made with love at Le Wagon
  </footer>
</html>

app/views/pages/about.html.erb
<h1>First web app for batch 264</h1>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>The spoon</h1>
<h3>Find the best restaurants in Tel Aviv</h3>

<form action="/restaurants" method="get">
  <input type="text" name="food_type" placeholder="What kind of food?">
  <input type="submit">
</form>

<br>

<p>Create a new restaurant</p>
<form action="/restaurants" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="address" placeholder="Address">
  <input type="submit">
</form>

app/views/restaurants/index.html.erb
<h1>Here are all restaurants in Tel Aviv</h1>

<ul>
  <% @restaurants.each do |id, restaurant| %>
  <li> <%= link_to restaurant[:name], restaurant_path(id) %></li>
  <% end %>
</ul>

app/views/restaurants/show.html.erb
<h1> <%= @restaurant[:name] %>   </h1>